FROM pgentile/debian
MAINTAINER Pierre Gentile <pierre.gentile.perso@gmail.com>

RUN apt-get install -y build-essential
RUN apt-get install -y ca-certificates curl unzip
RUN apt-get install -y git subversion
