elasticsearch:
    image: pgentile/elasticsearch
    ports:
        - "9200:9200"
    command:
        - "-Dhttp.publish_port=9200"

kibana:
    image: kibana
    links:
        - "elasticsearch:elasticsearch"
    ports:
        - "5601:5601"

stream2es:
    image: pgentile/elasticsearch-stream2es
    links:
        - "elasticsearch:elasticsearch"
