version: '2'

services:
  
  consul-server-1:
    build: consul-server
    stop_signal: SIGINT
    command:
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-server-2'
      - '-retry-join=consul-server-3'
    ports:
      - '8500:8500'
    networks:
      consul:
        aliases:
          - consul-server-1
      
  consul-server-2:
    build: consul-server
    stop_signal: SIGINT
    command:
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-server-1'
      - '-retry-join=consul-server-3'
    networks:
      consul:
        aliases:
          - consul-server-2
  
  consul-server-3:
    build: consul-server
    stop_signal: SIGINT
    command:
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-server-1'
      - '-retry-join=consul-server-2'
    networks:
      consul:
        aliases:
          - consul-server-3
  
  consul-client:
    image: pgentile/consul
    command: 
      - '-retry-join=consul-server-1'
      - '-retry-join=consul-server-2'
      - '-retry-join=consul-server-3'
      - '-retry-interval=5s'
    networks:
      - consul

networks:
  consul:
