version: "2"

services:

  mongo1:
    build: .
    networks:
      - mongors

  mongo2:
    build: .
    networks:
      - mongors

  mongo3:
    build: .
    networks:
      - mongors

  mongo4:
    build: .
    networks:
      - mongors

  mongo5:
    build: .
    networks:
      - mongors

networks:
  mongors:
    driver: bridge
