version: "2"

services:
  
  mongo1:
    build: .
    ports:
      - "27018:27017"
    networks:
      - mongors
      
  mongo2:
    build: .
    ports:
      - "27019:27017"
    networks:
      - mongors
      
  mongo3:
    build: .
    ports:
      - "27020:27017"
    networks:
      - mongors

networks:
  mongors:
    driver: bridge
