grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"

carbon:
  image: pgentile/go-carbon
  ports:
    - "2003:2003"
    - "2004:2004"
    - "7002:7002"

graphite:
  image: pgentile/graphite-api
  ports:
    - "8080:8080"
  volumes_from:
    - "carbon:ro"
