version: "2"

services:
  
  grafana:
    image: "grafana/grafana:master"
    ports:
      - "3000:3000"
    networks:
      - graphite
    links:
      - "graphite:graphite"

  carbon:
    image: pgentile/go-carbon
    ports:
      - "2003:2003"
    networks:
      - carbon

  graphite:
    image: pgentile/graphite-api
    volumes_from:
      - "carbon:ro"
    networks:
      - graphite
      - carbon
    links:
      - "carbon:carbon"

networks:
  graphite:
    driver: bridge
  carbon:
    driver: bridge
