version: '2'

services:
  
  consul-nantes-server-1:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=nantes-1'
      - '-dc=nantes'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-nantes-server-2'
      - '-retry-join=consul-nantes-server-3'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-paris-server-1'
      - '-retry-join-wan=consul-paris-server-2'
      - '-retry-join-wan=consul-paris-server-3'
    networks:
      consul:
        aliases:
          - consul-nantes-server-1
      
  consul-nantes-server-2:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=nantes-2'
      - '-dc=nantes'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-nantes-server-1'
      - '-retry-join=consul-nantes-server-3'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-paris-server-1'
      - '-retry-join-wan=consul-paris-server-2'
      - '-retry-join-wan=consul-paris-server-3'
    networks:
      consul:
        aliases:
          - consul-nantes-server-2
  
  consul-nantes-server-3:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=nantes-3'
      - '-dc=nantes'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-nantes-server-1'
      - '-retry-join=consul-nantes-server-2'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-paris-server-1'
      - '-retry-join-wan=consul-paris-server-2'
      - '-retry-join-wan=consul-paris-server-3'
    networks:
      consul:
        aliases:
          - consul-nantes-server-3
  
  consul-paris-server-1:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=paris-1'
      - '-dc=paris'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-paris-server-2'
      - '-retry-join=consul-paris-server-3'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-nantes-server-1'
      - '-retry-join-wan=consul-nantes-server-2'
      - '-retry-join-wan=consul-nantes-server-3'
    networks:
      consul:
        aliases:
          - consul-paris-server-1
      
  consul-paris-server-2:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=paris-2'
      - '-dc=paris'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-paris-server-1'
      - '-retry-join=consul-paris-server-3'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-nantes-server-1'
      - '-retry-join-wan=consul-nantes-server-2'
      - '-retry-join-wan=consul-nantes-server-3'
    networks:
      consul:
        aliases:
          - consul-paris-server-2
  
  consul-paris-server-3:
    image: pgentile/consul
    command:
      - '-server'
      - '-node=paris-3'
      - '-dc=paris'
      - '-bootstrap-expect=3'
      - '-retry-interval=5s'
      - '-retry-join=consul-paris-server-1'
      - '-retry-join=consul-paris-server-2'
      - '-retry-interval-wan=5s'
      - '-retry-join-wan=consul-nantes-server-1'
      - '-retry-join-wan=consul-nantes-server-2'
      - '-retry-join-wan=consul-nantes-server-3'
    networks:
      consul:
        aliases:
          - consul-paris-server-3
  
  consul-nantes-client-1:
    image: pgentile/consul
    command:
      - '-node=consul-nantes-client-1'
      - '-dc=nantes'
      - '-retry-interval=5s'
      - '-retry-join=consul-nantes-server-1'
      - '-retry-join=consul-nantes-server-2'
      - '-retry-join=consul-nantes-server-3'
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    networks:
      - consul
  
  consul-nantes-client-2:
    image: pgentile/consul
    command:
      - '-node=consul-nantes-client-2'
      - '-dc=nantes'
      - '-retry-interval=5s'
      - '-retry-join=consul-nantes-server-1'
      - '-retry-join=consul-nantes-server-2'
      - '-retry-join=consul-nantes-server-3'
    ports:
      - '8501:8500'
      - '8601:8600/udp'
    networks:
      - consul
  
  consul-paris-client-1:
    image: pgentile/consul
    command:
      - '-node=consul-paris-client-1'
      - '-dc=paris'
      - '-retry-interval=5s'
      - '-retry-join=consul-paris-server-1'
      - '-retry-join=consul-paris-server-2'
      - '-retry-join=consul-paris-server-3'
    ports:
      - '8510:8500'
      - '8610:8600/udp'
    networks:
      - consul
  
  consul-paris-client-2:
    image: pgentile/consul
    command:
      - '-node=consul-paris-client-2'
      - '-dc=paris'
      - '-retry-interval=5s'
      - '-retry-join=consul-paris-server-1'
      - '-retry-join=consul-paris-server-2'
      - '-retry-join=consul-paris-server-3'
    ports:
      - '8511:8500'
      - '8611:8600/udp'
    networks:
      - consul

networks:
  consul:
