HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html; charset=utf-8

<html>
<body>
<h1>503 Service Unavailable</h1>
<p style="color: red">I don't work for now...</p>
</body>
</html>