version: "2"

services:

  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    environment:
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 512
      ACTIVEMQ_STATIC_QUEUES: "test.sample1;test.sample2;test.sample3"
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
