version: "2"

services:

  zookeeper:
    image: pgentile/zookeeper
    ports:
      - "2181:2181"
    networks:
      - zookeeper

  kafka:
    image: pgentile/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOSTNAME: "192.168.99.100"
    networks:
      - zookeeper
    links:
      - "zookeeper:zookeeper"

networks:
  zookeeper:
    driver: bridge
