version: "2"

services:

  zookeeper:
    image: pgentile/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka

  kafka:
    image: pgentile/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
    networks:
      - kafka
    links:
      - "zookeeper:zookeeper"
  
#  kafka-manager:
#    image: pgentile/kafka-manager
#    ports:
#      - "9000:9000"
#    networks:
#      - kafka
#    links:
#      - "zookeeper:zookeeper"
#      - "kafka:kafka"

networks:
  kafka:
    driver: bridge
