version: "2"

services:

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb

  chronograf:
    image: chronograf
    ports:
      - "10000:10000"
    networks:
      - influxdb
    links:
      - influxdb

  # telegraf:
  #   build: ./telegraf
  #   networks:
  #     - influxdb
  #   links:
  #     - influxdb
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    networks:
      - influxdb
    links:
      - influxdb

networks:
  influxdb:
    driver: bridge
